export enum Permission {
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_WORKFLOWS = 'VIEW_WORKFLOWS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  EDIT_WORKFLOW = 'EDIT_WORKFLOW',
  CREATE_WORKFLOW = 'CREATE_WORKFLOW',
  ADMIN_ACCESS = 'ADMIN_ACCESS',
}
